/*
 * test_codec.c — the decoders, against real files.
 *
 * There were no codec tests at all, which is why "incomplete MP4 sample
 * tables" reached a device. The fixtures are generated by
 * tests/fixtures/audio/make.sh with ffmpeg, so they are real MP4 and MP3
 * files rather than hand-built byte strings that only prove the parser agrees
 * with whoever wrote the test.
 *
 * Two MP4 variants matter and are both covered: moov at the end, which is what
 * an encoder writes by default, and moov at the front, which is what
 * +faststart produces. A parser can easily handle one and not the other.
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "../../src/codec/tp_decode.h"
#include "../../src/codec/tp_mp4.h"

static int checks, failures;

#define CHECK(cond, ...)                                                      \
    do {                                                                      \
        checks++;                                                             \
        if (!(cond)) {                                                        \
            failures++;                                                       \
            printf("  FAIL %s:%d  ", __FILE__, __LINE__);                     \
            printf(__VA_ARGS__);                                              \
            printf("\n");                                                     \
        }                                                                     \
    } while (0)

#define FIX "tests/fixtures/audio/"

static void test_mp4_tables(const char *name)
{
    char path[256], err[256];
    snprintf(path, sizeof path, FIX "%s", name);
    err[0] = 0;

    struct tp_mp4 *m = tp_mp4_open(path, err, sizeof err);
    CHECK(m != NULL, "%s: %s", name, err[0] ? err : "open returned NULL");
    if (!m)
        return;

    printf("  %-22s %s %d Hz %d ch, %u frames\n", name,
           tp_mp4_codec(m), tp_mp4_sample_rate(m), tp_mp4_channels(m),
           tp_mp4_frame_count(m));

    CHECK(tp_mp4_is_aac(m), "%s: not recognised as AAC", name);
    CHECK(tp_mp4_sample_rate(m) == 44100, "%s: rate %d", name,
          tp_mp4_sample_rate(m));
    CHECK(tp_mp4_channels(m) == 2, "%s: %d channels", name,
          tp_mp4_channels(m));
    CHECK(tp_mp4_frame_count(m) > 0, "%s: no frames", name);

    size_t asc_len = 0;
    CHECK(tp_mp4_asc(m, &asc_len) != NULL && asc_len > 0,
          "%s: no AudioSpecificConfig - the decoder cannot be configured",
          name);

    tp_mp4_close(m);
}

/* Decode the whole file and report what came out. A decoder that opens and
   then produces nothing is the failure that looks like success. */
static void test_decode(const char *name, int want_rate, int want_ch)
{
    char path[256], err[256];
    snprintf(path, sizeof path, FIX "%s", name);
    err[0] = 0;

    struct tp_dec *d = tp_dec_open(path, err, sizeof err);
    CHECK(d != NULL, "%s: %s", name, err[0] ? err : "open returned NULL");
    if (!d)
        return;

    CHECK(tp_dec_sample_rate(d) == want_rate, "%s: rate %d, wanted %d",
          name, tp_dec_sample_rate(d), want_rate);
    CHECK(tp_dec_channels(d) == want_ch, "%s: %d channels, wanted %d",
          name, tp_dec_channels(d), want_ch);

    short buf[4096];
    long total = 0;
    int reads = 0, nonsilent = 0;
    for (;;) {
        int n = tp_dec_read(d, buf, (int)(sizeof buf / sizeof buf[0]));
        if (n <= 0)
            break;
        total += n;
        reads++;
        for (int i = 0; i < n; i++) {
            if (buf[i] > 512 || buf[i] < -512) { nonsilent++; break; }
        }
        if (reads > 20000)
            break;                       /* a decoder that never ends */
    }

    double secs = want_rate ? (double)total / (want_ch * want_rate) : 0.0;
    printf("  %-22s %ld samples over %d reads, %.2f s, %d non-silent\n",
           name, total, reads, secs, nonsilent);

    CHECK(total > 0, "%s: decoded nothing at all", name);
    /* The fixtures are three seconds of a 440 Hz tone. Anything that decodes
       to silence has opened the file and then failed quietly, which is the
       exact failure being tested for. */
    CHECK(nonsilent > 0, "%s: decoded only silence", name);
    CHECK(secs > 2.0 && secs < 4.0, "%s: decoded %.2f s, expected about 3",
          name, secs);

    tp_dec_close(d);
}

int main(void)
{
    printf("tinypod codec tests\n\n== MP4 sample tables\n");
    test_mp4_tables("aac-faststart.m4a");
    test_mp4_tables("aac-moov-end.m4a");

    printf("\n== decoding\n");
    test_decode("aac-faststart.m4a", 44100, 2);
    test_decode("aac-moov-end.m4a", 44100, 2);
    test_decode("test.mp3", 44100, 2);

    printf("\n%d checks, %d failures\n", checks, failures);
    return failures ? 1 : 0;
}
